# Generated by Django 3.2.8 on 2021-11-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekMotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Titel')),
                ('date', models.DateField(verbose_name='Datum')),
                ('gospels', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Evangelien')),
                ('epistle', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Epistel')),
                ('old_testament', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='AT')),
                ('lecture', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Predigt')),
                ('motto_short', models.CharField(default='', max_length=100, null=True, verbose_name='Wochenspruch kurz')),
                ('motto_long', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Wochenspruch Lang')),
                ('motto_api', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Wochenspruch API')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
            ],
            options={
                'verbose_name_plural': 'WeekMottos',
            },
        ),
    ]
