# Generated by Django 4.0 on 2021-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filePath', models.CharField(max_length=400, unique=True, verbose_name='Dateipfad')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('copyrights', models.CharField(blank=True, max_length=500, null=True, verbose_name='(c)')),
                ('addCopyrightInfo', models.CharField(blank=True, max_length=500, null=True, verbose_name='AddCopyrightInfo')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Author')),
                ('bible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bible')),
                ('CCLI', models.IntegerField(blank=True, null=True, verbose_name='CCLI')),
                ('categories', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categories')),
                ('churchSongID', models.CharField(blank=True, max_length=100, null=True, verbose_name='ChurchSongID')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('editor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Editor')),
                ('format', models.CharField(blank=True, max_length=100, null=True, verbose_name='Format')),
                ('key', models.CharField(blank=True, max_length=20, null=True, verbose_name='Key')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords')),
                ('lang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lang')),
                ('langCount', models.IntegerField(blank=True, null=True, verbose_name='LangCount')),
                ('melody', models.CharField(blank=True, max_length=100, null=True, verbose_name='Melody')),
                ('natCopyright', models.CharField(blank=True, max_length=500, null=True, verbose_name='NatCopyright')),
                ('oTitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='OTitle')),
                ('quickFind', models.CharField(blank=True, max_length=50, null=True, verbose_name='QuickFind')),
                ('rights', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rights')),
                ('songbook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Songbook')),
                ('speed', models.CharField(blank=True, max_length=20, null=True, verbose_name='Speed')),
                ('titleFormat', models.CharField(blank=True, max_length=20, null=True, verbose_name='TitleFormat')),
                ('titleLang2', models.CharField(blank=True, max_length=100, null=True, verbose_name='TitleLang2')),
                ('titleLang3', models.CharField(blank=True, max_length=100, null=True, verbose_name='TitleLang3')),
                ('titleLang4', models.CharField(blank=True, max_length=100, null=True, verbose_name='TitleLang4')),
                ('translation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Translation')),
                ('verseOrder', models.CharField(blank=True, max_length=500, null=True, verbose_name='VerseOrder')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Version')),
                ('file_md5_hash', models.CharField(max_length=32, verbose_name='md5-Hash')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
