# Generated by Django 4.0.5 on 2022-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sended_Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_mail', models.CharField(max_length=200, verbose_name='Empfänger-Mailadresse')),
                ('sender_mail', models.CharField(max_length=200, verbose_name='Sender-Mailadresse')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('subject', models.CharField(max_length=200, verbose_name='Betreff')),
                ('error_massage', models.TextField(blank=True, null=True, verbose_name='Error-Nachricht')),
                ('send_status', models.BooleanField(verbose_name='Gedendet')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
            ],
            options={
                'verbose_name_plural': 'Sended_Emails',
            },
        ),
    ]
