# Generated by Django 4.0.5 on 2022-11-04 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_sended_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_folder', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='SongOrdner Pfad')),
                ('powerpoin_vorlage', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='PowerPoint-Vorlage Pfad')),
                ('base_url', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='CT Basis-Url')),
                ('login_token', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Login Token')),
                ('email_user_name', models.CharField(max_length=50, verbose_name='Email-Absender-Name')),
                ('email_user', models.EmailField(max_length=254, verbose_name='Email-Absender')),
                ('email_password', models.CharField(max_length=256, verbose_name='Email-Passwort')),
                ('name_error_reciever', models.CharField(max_length=50, verbose_name='Email-ErrorEmpfaenger-Name')),
                ('email_error_receiver', models.EmailField(max_length=254, verbose_name='Email-Absender')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
            ],
            options={
                'verbose_name_plural': 'AdminSettings',
            },
        ),
        migrations.CreateModel(
            name='RenderdSongbeamerFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('songs', models.CharField(blank=True, max_length=256, null=True, verbose_name='Countdown Pfad')),
                ('countdown_file_path', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Countdown Pfad')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.agenda')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RenderdSongbeamerFiles',
            },
        ),
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Countdown Pfad')),
                ('gender', models.CharField(max_length=20, verbose_name='Geschlecht')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AdditionalUserInfos',
            },
        ),
    ]
