# Generated by Django 4.0.5 on 2022-11-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_adminsetting_renderdsongbeamerfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluserinfo',
            old_name='d',
            new_name='countdown_file_path',
        ),
        migrations.RemoveField(
            model_name='renderdsongbeamerfile',
            name='countdown_file_path',
        ),
    ]
