# Generated by Django 4.0.5 on 2022-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_d_additionaluserinfo_countdown_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsetting',
            name='email_error_receiver',
            field=models.EmailField(max_length=254, verbose_name='Email-ErrorEmpfaenger'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='email_password',
            field=models.CharField(max_length=256, verbose_name='Email-Absender-Passwort'),
        ),
        migrations.AlterField(
            model_name='renderdsongbeamerfile',
            name='songs',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Songs'),
        ),
    ]
