# Generated by Django 4.0.5 on 2022-11-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_adminsetting_email_error_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekmotto',
            name='motto_luther_modern',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Wochenspruch Luther'),
        ),
    ]
