# Generated by Django 4.0.5 on 2022-11-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_weekmotto_motto_luther_modern'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderdPowerpointFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.agenda')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RenderdPowerpointFiles',
            },
        ),
    ]
